### ISSUE TITLE
If trying press more than once "FLUID EXAMPLE" to cause the bug.

### ISSUE THREAD

**Issue by Sieg-sol-fried** [jonobr1/stalactite#8]
Two or more times, performing initialization would take over the previous value.
It would go shifted more and more is bidding up movement above.

**Comment by jonobr1** [comment]
That is a bug! Thanks for filing!

**Comment by jonobr1** [comment]
This commit should fix it: https://github.com/jonobr1/stalactite/commit/bbf37154c898b76f933903d0ac6079bc3b66b761
